spring.application.name=CloudGateway

spring.cloud.gateway.routes[0].id=AuthenticationService  
spring.cloud.gateway.routes[0].uri=http://localhost:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

#spring.cloud.gateway.routes[1].id=DepartmentService
#spring.cloud.gateway.routes[1].uri=http://localhost:8080
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/department/
#spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=CourseService
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/course/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=EnrollmentService
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/enrollement/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Customize the port for Spring Boot embedded server
server.port=8084

# Enable Spring Boot Actuator for monitoring
management.endpoints.web.exposure.include=health,info

# Optionally, configure logging
logging.level.org.springframework.web=DEBUG

spring.cloud.config.enabled=false
spring.config.import=optional:configserver:

spring.main.web-application-type=reactive

